version: "3.3"
services:
  traffic-sign-recognition-server:
    platform: linux/x86_64
    build: ./TrafficSignRecognitionServer
    volumes:
      - ./TrafficSignRecognitionServer/src:/code
    ports:
      - "8080:8080"
    command: sh -c "python main.py"
